### ISSUE TITLE
Tilt effect crashes when enabled

### ISSUE THREAD

**Issue by Ender121** [patzly/doodle-android#65] opened 2022-08-17 00:55 UTC
Everytime when tilt effect is turned on the app starts to freeze or crashes.

 - Device: [Google Pixel 6 Pro]
 - OS: [Pixel Experience Plus]
 - Version [Android 12L]
 - I can't access this phone anymore so I'm sorry for lack of information

**Comment by patzly** [comment] 2022-08-21 05:31
Thank you for reporting, I will close this issue because I cannot reproduce it on my Pixel 6 with 12L and 13. Also I can't find a reason in code, without a crashlog this is sadly impossible to find.

**Closed by patzly** 2022-08-21 05:31 UTC
Labels: bug

**Comment by Ender121** [comment] 2022-08-26 00:11
Welp that's unfortunate.
