### ISSUE TITLE
The main interface can be displayed, but the options interface cannot be displayed (blank)

### ISSUE THREAD

**Issue by gytxtx** [patzly/doodle-android#101] opened 2024-03-15 02:25 UTC
**Describe the bug**

Unable to display options interface.

**To Reproduce**

1. Open the app.
2. Click on any option menu, such as "About"
3. Recurrence error (the interface is blank)

**Expected behavior**

The software options interface displays normally.

**Screenshots**

![超级截屏_20240315_102228](https://github.com/patzly/doodle-android/assets/62281844/cd8bebad-4601-41fe-bd3b-7edfbb09d104)

![超级截屏_20240315_102235](https://github.com/patzly/doodle-android/assets/62281844/7882838f-5ff0-4ad0-b73a-e9b756701323)

**Usage information (please complete the following):**

 - Device: Vivo X9 Plus
 - OS: Android 7.1.2
 - Version: 5.6.1

**Comment by patzly** [comment] 2024-10-31 17:02
Please download the latest version on GitHub (or in a few days on Google Play)! Then please let me know if it's finally working with v6.0.0.

**Comment by gytxtx** [comment] 2024-11-01 08:16
Thank you for your response. I have downloaded the latest version (v6.0.0) from GitHub, but I am still experiencing the same issue. The options interface remains blank when I try to access it.

Could you please advise on any further steps I can take to troubleshoot this problem?

Thank you!

![截屏_20241101_160359](https://github.com/user-attachments/assets/cb74bddc-fa94-4123-b973-a2b9c8bd2321)

![截屏_20241101_160403](https://github.com/user-attachments/assets/7b0c7248-60a3-4237-8bba-143bfd7ca973)

![截屏_20241101_160503](https://github.com/user-attachments/assets/3fbe2b0c-5a7a-46b1-bc46-096199280549)

[Related Screen Recordings](https://github.com/gytxtx/Miscellaneous/raw/refs/heads/main/%E5%BD%95%E5%B1%8F_20241101_160315.mp4)

**Comment by patzly** [comment] 2024-11-14 09:40
Duplicate of #90, I will use that issue for problem tracking.

**Closed by patzly** 2024-11-14 09:40 UTC
Labels: bug
