### ISSUE TITLE
Wallpaper not working on lock screen

### ISSUE THREAD

**Issue by UbaidYafiHanzah** [patzly/doodle-android#48] opened 2022-01-13 15:06 UTC
I tried to set the wallpaper and it worked, but not on the lock screen. Was it my fault? I want to know the answer. The others work fine. Thank you!

**Comment by patzly** [comment] 2022-01-14 00:00
Hi, could you please read the troubleshooting section of the info sheet (tap on the info card on the start page)? There you should find the answer, but please give me your device name here so I can help you more specifically.

**Comment by patzly** [comment] 2022-07-12 22:29
I will close this issue because I need more info on how the bug affects the wallpaper on lockscreen and what device was used. Maybe it's a duplicate of #41 and/or #59. Please feel free to reopen it if I am wrong and if you can provide more information to reproduce this issue.

**Closed by patzly** 2022-07-12 22:29 UTC
Labels: bug, invalid

**Comment by tylvn** [comment] 2022-09-14 11:44
I encountered this problem in Huawei phone. There have no changes of wallpaper on lock screen when installing and using doodle in Huawei phone.

**Comment by patzly** [comment] 2022-09-14 18:47
@tylvn What happens if you install other live wallpapers from Google Play? Are they also only applied to homescreen and not to the lockscreen?

**Comment by tylvn** [comment] 2022-09-15 15:21
> Are they also only applied to homescreen and not to the lockscreen?

Yes.

**Comment by patzly** [comment] 2022-09-15 18:49
Oh then it is caused by Huawei, they have a very weird wallpaper behavior nobody can understand. If other live wallpaper apps have the same behavior as Doodle on your phone, then it simply means that Huawei has again broken some basic Android behavior... I sadly can't do anything for you at this point, maybe you can google for a solution for your phone like I have written in the help dialog in the app, but I'm not sure whether there exists a solution. I can only recommend you to buy your next phone from a brand other than Huawei, their system modifications are really destructive for app developers.

**Comment by tylvn** [comment] 2022-09-16 15:13
> If other live wallpaper apps have the same behavior as Doodle on your phone, then it simply means that Huawei has again broken some basic Android behavior.

Thank you for your explanation. 👍

**Comment by UbaidYafiHanzah** [comment] 2022-09-20 21:13
Ok, thanks.

**Comment by UbaidYafiHanzah** [comment] 2022-10-11 09:29
I am using Xiaomi Redmi 6 (cerus) another live wallpaper is work. Super
wallpaper (from Xiaomi) work too.
